int _putchar(char r);
int _islower(int r);
int _isalpha(int r);
int _abs(int q);
int _isupper(int r);
int _isdigit(int r);
int _strlen(char *p);
void _puts(char *p);
char *_strcpy(char *dest, char *src);
int _atoi(char *p);
char *_strcat(char *dest, char *src);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
int _strcmp(char *p1, char *p2);
char *_memset(char *p, char m, unsigned int q);
char *_memcpy(char *dest, char *src, unsigned int q);
char *_strchr(char *p, char r);
unsigned int _strspn(char *p, char *accept);
char *_strpbrk(char *p, char *accept);
char *_strstr(char *haystack, char *needle);
